name: 'catalyst'
version: 3.0.0
description: The only dependency injection container for Dart you'll ever need
homepage: https://github.com/mintware-de/catalyst
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.16.8