name: 'catalyst'
version: 3.0.0
description: The only dependency injection container for Dart you'll ever need
author: Julian Finkler <julian@mintware.de>
homepage: https://github.com/Devtronic/catalyst
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.16.8