name: 'catalyst'
version: 0.0.1
description: The only dependency injection container for Dart you'll ever need
author: Julian Finkler <julian@mintware.de>
homepage: https://github.com/Devtronic/catalyst
environment:
  sdk: '>=1.24.3 <2.0.0'
dev_dependencies:
  test: ^0.12.34
  dart_coveralls: "^0.5.0"