name: 'catalyst'
version: 1.1.0
description: The only dependency injection container for Dart you'll ever need
author: Julian Finkler <julian@mintware.de>
homepage: https://github.com/Devtronic/catalyst
environment:
  sdk: '>=1.24.3 <2.0.0'
dev_dependencies:
  test: ^0.12.34